//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace MrktSimDb {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class OptInfo : DataSet {
        
        private optimization_explore_modeDataTable tableoptimization_explore_mode;
        
        private optimization_mode_execDataTable tableoptimization_mode_exec;
        
        private optimization_optimize_forDataTable tableoptimization_optimize_for;
        
        private optimization_paramsDataTable tableoptimization_params;
        
        private optimization_planDataTable tableoptimization_plan;
        
        public OptInfo() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected OptInfo(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["optimization_explore_mode"] != null)) {
                    this.Tables.Add(new optimization_explore_modeDataTable(ds.Tables["optimization_explore_mode"]));
                }
                if ((ds.Tables["optimization_mode_exec"] != null)) {
                    this.Tables.Add(new optimization_mode_execDataTable(ds.Tables["optimization_mode_exec"]));
                }
                if ((ds.Tables["optimization_optimize_for"] != null)) {
                    this.Tables.Add(new optimization_optimize_forDataTable(ds.Tables["optimization_optimize_for"]));
                }
                if ((ds.Tables["optimization_params"] != null)) {
                    this.Tables.Add(new optimization_paramsDataTable(ds.Tables["optimization_params"]));
                }
                if ((ds.Tables["optimization_plan"] != null)) {
                    this.Tables.Add(new optimization_planDataTable(ds.Tables["optimization_plan"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public optimization_explore_modeDataTable optimization_explore_mode {
            get {
                return this.tableoptimization_explore_mode;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public optimization_mode_execDataTable optimization_mode_exec {
            get {
                return this.tableoptimization_mode_exec;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public optimization_optimize_forDataTable optimization_optimize_for {
            get {
                return this.tableoptimization_optimize_for;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public optimization_paramsDataTable optimization_params {
            get {
                return this.tableoptimization_params;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public optimization_planDataTable optimization_plan {
            get {
                return this.tableoptimization_plan;
            }
        }
        
        public override DataSet Clone() {
            OptInfo cln = ((OptInfo)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["optimization_explore_mode"] != null)) {
                this.Tables.Add(new optimization_explore_modeDataTable(ds.Tables["optimization_explore_mode"]));
            }
            if ((ds.Tables["optimization_mode_exec"] != null)) {
                this.Tables.Add(new optimization_mode_execDataTable(ds.Tables["optimization_mode_exec"]));
            }
            if ((ds.Tables["optimization_optimize_for"] != null)) {
                this.Tables.Add(new optimization_optimize_forDataTable(ds.Tables["optimization_optimize_for"]));
            }
            if ((ds.Tables["optimization_params"] != null)) {
                this.Tables.Add(new optimization_paramsDataTable(ds.Tables["optimization_params"]));
            }
            if ((ds.Tables["optimization_plan"] != null)) {
                this.Tables.Add(new optimization_planDataTable(ds.Tables["optimization_plan"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableoptimization_explore_mode = ((optimization_explore_modeDataTable)(this.Tables["optimization_explore_mode"]));
            if ((this.tableoptimization_explore_mode != null)) {
                this.tableoptimization_explore_mode.InitVars();
            }
            this.tableoptimization_mode_exec = ((optimization_mode_execDataTable)(this.Tables["optimization_mode_exec"]));
            if ((this.tableoptimization_mode_exec != null)) {
                this.tableoptimization_mode_exec.InitVars();
            }
            this.tableoptimization_optimize_for = ((optimization_optimize_forDataTable)(this.Tables["optimization_optimize_for"]));
            if ((this.tableoptimization_optimize_for != null)) {
                this.tableoptimization_optimize_for.InitVars();
            }
            this.tableoptimization_params = ((optimization_paramsDataTable)(this.Tables["optimization_params"]));
            if ((this.tableoptimization_params != null)) {
                this.tableoptimization_params.InitVars();
            }
            this.tableoptimization_plan = ((optimization_planDataTable)(this.Tables["optimization_plan"]));
            if ((this.tableoptimization_plan != null)) {
                this.tableoptimization_plan.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "OptInfo";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/OptInfo.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableoptimization_explore_mode = new optimization_explore_modeDataTable();
            this.Tables.Add(this.tableoptimization_explore_mode);
            this.tableoptimization_mode_exec = new optimization_mode_execDataTable();
            this.Tables.Add(this.tableoptimization_mode_exec);
            this.tableoptimization_optimize_for = new optimization_optimize_forDataTable();
            this.Tables.Add(this.tableoptimization_optimize_for);
            this.tableoptimization_params = new optimization_paramsDataTable();
            this.Tables.Add(this.tableoptimization_params);
            this.tableoptimization_plan = new optimization_planDataTable();
            this.Tables.Add(this.tableoptimization_plan);
        }
        
        private bool ShouldSerializeoptimization_explore_mode() {
            return false;
        }
        
        private bool ShouldSerializeoptimization_mode_exec() {
            return false;
        }
        
        private bool ShouldSerializeoptimization_optimize_for() {
            return false;
        }
        
        private bool ShouldSerializeoptimization_params() {
            return false;
        }
        
        private bool ShouldSerializeoptimization_plan() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void optimization_explore_modeRowChangeEventHandler(object sender, optimization_explore_modeRowChangeEvent e);
        
        public delegate void optimization_mode_execRowChangeEventHandler(object sender, optimization_mode_execRowChangeEvent e);
        
        public delegate void optimization_optimize_forRowChangeEventHandler(object sender, optimization_optimize_forRowChangeEvent e);
        
        public delegate void optimization_paramsRowChangeEventHandler(object sender, optimization_paramsRowChangeEvent e);
        
        public delegate void optimization_planRowChangeEventHandler(object sender, optimization_planRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_explore_modeDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnexplore_mode_id;
            
            private DataColumn columnexplore_mode;
            
            internal optimization_explore_modeDataTable() : 
                    base("optimization_explore_mode") {
                this.InitClass();
            }
            
            internal optimization_explore_modeDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn explore_mode_idColumn {
                get {
                    return this.columnexplore_mode_id;
                }
            }
            
            internal DataColumn explore_modeColumn {
                get {
                    return this.columnexplore_mode;
                }
            }
            
            public optimization_explore_modeRow this[int index] {
                get {
                    return ((optimization_explore_modeRow)(this.Rows[index]));
                }
            }
            
            public event optimization_explore_modeRowChangeEventHandler optimization_explore_modeRowChanged;
            
            public event optimization_explore_modeRowChangeEventHandler optimization_explore_modeRowChanging;
            
            public event optimization_explore_modeRowChangeEventHandler optimization_explore_modeRowDeleted;
            
            public event optimization_explore_modeRowChangeEventHandler optimization_explore_modeRowDeleting;
            
            public void Addoptimization_explore_modeRow(optimization_explore_modeRow row) {
                this.Rows.Add(row);
            }
            
            public optimization_explore_modeRow Addoptimization_explore_modeRow(System.Byte explore_mode_id, string explore_mode) {
                optimization_explore_modeRow rowoptimization_explore_modeRow = ((optimization_explore_modeRow)(this.NewRow()));
                rowoptimization_explore_modeRow.ItemArray = new object[] {
                        explore_mode_id,
                        explore_mode};
                this.Rows.Add(rowoptimization_explore_modeRow);
                return rowoptimization_explore_modeRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                optimization_explore_modeDataTable cln = ((optimization_explore_modeDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new optimization_explore_modeDataTable();
            }
            
            internal void InitVars() {
                this.columnexplore_mode_id = this.Columns["explore_mode_id"];
                this.columnexplore_mode = this.Columns["explore_mode"];
            }
            
            private void InitClass() {
                this.columnexplore_mode_id = new DataColumn("explore_mode_id", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnexplore_mode_id);
                this.columnexplore_mode = new DataColumn("explore_mode", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnexplore_mode);
                this.columnexplore_mode_id.AllowDBNull = false;
                this.columnexplore_mode.AllowDBNull = false;
            }
            
            public optimization_explore_modeRow Newoptimization_explore_modeRow() {
                return ((optimization_explore_modeRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new optimization_explore_modeRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(optimization_explore_modeRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.optimization_explore_modeRowChanged != null)) {
                    this.optimization_explore_modeRowChanged(this, new optimization_explore_modeRowChangeEvent(((optimization_explore_modeRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.optimization_explore_modeRowChanging != null)) {
                    this.optimization_explore_modeRowChanging(this, new optimization_explore_modeRowChangeEvent(((optimization_explore_modeRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.optimization_explore_modeRowDeleted != null)) {
                    this.optimization_explore_modeRowDeleted(this, new optimization_explore_modeRowChangeEvent(((optimization_explore_modeRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.optimization_explore_modeRowDeleting != null)) {
                    this.optimization_explore_modeRowDeleting(this, new optimization_explore_modeRowChangeEvent(((optimization_explore_modeRow)(e.Row)), e.Action));
                }
            }
            
            public void Removeoptimization_explore_modeRow(optimization_explore_modeRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_explore_modeRow : DataRow {
            
            private optimization_explore_modeDataTable tableoptimization_explore_mode;
            
            internal optimization_explore_modeRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableoptimization_explore_mode = ((optimization_explore_modeDataTable)(this.Table));
            }
            
            public System.Byte explore_mode_id {
                get {
                    return ((System.Byte)(this[this.tableoptimization_explore_mode.explore_mode_idColumn]));
                }
                set {
                    this[this.tableoptimization_explore_mode.explore_mode_idColumn] = value;
                }
            }
            
            public string explore_mode {
                get {
                    return ((string)(this[this.tableoptimization_explore_mode.explore_modeColumn]));
                }
                set {
                    this[this.tableoptimization_explore_mode.explore_modeColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_explore_modeRowChangeEvent : EventArgs {
            
            private optimization_explore_modeRow eventRow;
            
            private DataRowAction eventAction;
            
            public optimization_explore_modeRowChangeEvent(optimization_explore_modeRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public optimization_explore_modeRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_mode_execDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnmode_exec_id;
            
            private DataColumn columnmode_exec;
            
            internal optimization_mode_execDataTable() : 
                    base("optimization_mode_exec") {
                this.InitClass();
            }
            
            internal optimization_mode_execDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn mode_exec_idColumn {
                get {
                    return this.columnmode_exec_id;
                }
            }
            
            internal DataColumn mode_execColumn {
                get {
                    return this.columnmode_exec;
                }
            }
            
            public optimization_mode_execRow this[int index] {
                get {
                    return ((optimization_mode_execRow)(this.Rows[index]));
                }
            }
            
            public event optimization_mode_execRowChangeEventHandler optimization_mode_execRowChanged;
            
            public event optimization_mode_execRowChangeEventHandler optimization_mode_execRowChanging;
            
            public event optimization_mode_execRowChangeEventHandler optimization_mode_execRowDeleted;
            
            public event optimization_mode_execRowChangeEventHandler optimization_mode_execRowDeleting;
            
            public void Addoptimization_mode_execRow(optimization_mode_execRow row) {
                this.Rows.Add(row);
            }
            
            public optimization_mode_execRow Addoptimization_mode_execRow(System.Byte mode_exec_id, string mode_exec) {
                optimization_mode_execRow rowoptimization_mode_execRow = ((optimization_mode_execRow)(this.NewRow()));
                rowoptimization_mode_execRow.ItemArray = new object[] {
                        mode_exec_id,
                        mode_exec};
                this.Rows.Add(rowoptimization_mode_execRow);
                return rowoptimization_mode_execRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                optimization_mode_execDataTable cln = ((optimization_mode_execDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new optimization_mode_execDataTable();
            }
            
            internal void InitVars() {
                this.columnmode_exec_id = this.Columns["mode_exec_id"];
                this.columnmode_exec = this.Columns["mode_exec"];
            }
            
            private void InitClass() {
                this.columnmode_exec_id = new DataColumn("mode_exec_id", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnmode_exec_id);
                this.columnmode_exec = new DataColumn("mode_exec", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnmode_exec);
                this.columnmode_exec_id.AllowDBNull = false;
                this.columnmode_exec.AllowDBNull = false;
            }
            
            public optimization_mode_execRow Newoptimization_mode_execRow() {
                return ((optimization_mode_execRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new optimization_mode_execRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(optimization_mode_execRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.optimization_mode_execRowChanged != null)) {
                    this.optimization_mode_execRowChanged(this, new optimization_mode_execRowChangeEvent(((optimization_mode_execRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.optimization_mode_execRowChanging != null)) {
                    this.optimization_mode_execRowChanging(this, new optimization_mode_execRowChangeEvent(((optimization_mode_execRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.optimization_mode_execRowDeleted != null)) {
                    this.optimization_mode_execRowDeleted(this, new optimization_mode_execRowChangeEvent(((optimization_mode_execRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.optimization_mode_execRowDeleting != null)) {
                    this.optimization_mode_execRowDeleting(this, new optimization_mode_execRowChangeEvent(((optimization_mode_execRow)(e.Row)), e.Action));
                }
            }
            
            public void Removeoptimization_mode_execRow(optimization_mode_execRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_mode_execRow : DataRow {
            
            private optimization_mode_execDataTable tableoptimization_mode_exec;
            
            internal optimization_mode_execRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableoptimization_mode_exec = ((optimization_mode_execDataTable)(this.Table));
            }
            
            public System.Byte mode_exec_id {
                get {
                    return ((System.Byte)(this[this.tableoptimization_mode_exec.mode_exec_idColumn]));
                }
                set {
                    this[this.tableoptimization_mode_exec.mode_exec_idColumn] = value;
                }
            }
            
            public string mode_exec {
                get {
                    return ((string)(this[this.tableoptimization_mode_exec.mode_execColumn]));
                }
                set {
                    this[this.tableoptimization_mode_exec.mode_execColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_mode_execRowChangeEvent : EventArgs {
            
            private optimization_mode_execRow eventRow;
            
            private DataRowAction eventAction;
            
            public optimization_mode_execRowChangeEvent(optimization_mode_execRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public optimization_mode_execRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_optimize_forDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnoptimize_for_id;
            
            private DataColumn columnoptimize_for;
            
            internal optimization_optimize_forDataTable() : 
                    base("optimization_optimize_for") {
                this.InitClass();
            }
            
            internal optimization_optimize_forDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn optimize_for_idColumn {
                get {
                    return this.columnoptimize_for_id;
                }
            }
            
            internal DataColumn optimize_forColumn {
                get {
                    return this.columnoptimize_for;
                }
            }
            
            public optimization_optimize_forRow this[int index] {
                get {
                    return ((optimization_optimize_forRow)(this.Rows[index]));
                }
            }
            
            public event optimization_optimize_forRowChangeEventHandler optimization_optimize_forRowChanged;
            
            public event optimization_optimize_forRowChangeEventHandler optimization_optimize_forRowChanging;
            
            public event optimization_optimize_forRowChangeEventHandler optimization_optimize_forRowDeleted;
            
            public event optimization_optimize_forRowChangeEventHandler optimization_optimize_forRowDeleting;
            
            public void Addoptimization_optimize_forRow(optimization_optimize_forRow row) {
                this.Rows.Add(row);
            }
            
            public optimization_optimize_forRow Addoptimization_optimize_forRow(System.Byte optimize_for_id, string optimize_for) {
                optimization_optimize_forRow rowoptimization_optimize_forRow = ((optimization_optimize_forRow)(this.NewRow()));
                rowoptimization_optimize_forRow.ItemArray = new object[] {
                        optimize_for_id,
                        optimize_for};
                this.Rows.Add(rowoptimization_optimize_forRow);
                return rowoptimization_optimize_forRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                optimization_optimize_forDataTable cln = ((optimization_optimize_forDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new optimization_optimize_forDataTable();
            }
            
            internal void InitVars() {
                this.columnoptimize_for_id = this.Columns["optimize_for_id"];
                this.columnoptimize_for = this.Columns["optimize_for"];
            }
            
            private void InitClass() {
                this.columnoptimize_for_id = new DataColumn("optimize_for_id", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnoptimize_for_id);
                this.columnoptimize_for = new DataColumn("optimize_for", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnoptimize_for);
                this.columnoptimize_for_id.AllowDBNull = false;
                this.columnoptimize_for.AllowDBNull = false;
            }
            
            public optimization_optimize_forRow Newoptimization_optimize_forRow() {
                return ((optimization_optimize_forRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new optimization_optimize_forRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(optimization_optimize_forRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.optimization_optimize_forRowChanged != null)) {
                    this.optimization_optimize_forRowChanged(this, new optimization_optimize_forRowChangeEvent(((optimization_optimize_forRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.optimization_optimize_forRowChanging != null)) {
                    this.optimization_optimize_forRowChanging(this, new optimization_optimize_forRowChangeEvent(((optimization_optimize_forRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.optimization_optimize_forRowDeleted != null)) {
                    this.optimization_optimize_forRowDeleted(this, new optimization_optimize_forRowChangeEvent(((optimization_optimize_forRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.optimization_optimize_forRowDeleting != null)) {
                    this.optimization_optimize_forRowDeleting(this, new optimization_optimize_forRowChangeEvent(((optimization_optimize_forRow)(e.Row)), e.Action));
                }
            }
            
            public void Removeoptimization_optimize_forRow(optimization_optimize_forRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_optimize_forRow : DataRow {
            
            private optimization_optimize_forDataTable tableoptimization_optimize_for;
            
            internal optimization_optimize_forRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableoptimization_optimize_for = ((optimization_optimize_forDataTable)(this.Table));
            }
            
            public System.Byte optimize_for_id {
                get {
                    return ((System.Byte)(this[this.tableoptimization_optimize_for.optimize_for_idColumn]));
                }
                set {
                    this[this.tableoptimization_optimize_for.optimize_for_idColumn] = value;
                }
            }
            
            public string optimize_for {
                get {
                    return ((string)(this[this.tableoptimization_optimize_for.optimize_forColumn]));
                }
                set {
                    this[this.tableoptimization_optimize_for.optimize_forColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_optimize_forRowChangeEvent : EventArgs {
            
            private optimization_optimize_forRow eventRow;
            
            private DataRowAction eventAction;
            
            public optimization_optimize_forRowChangeEvent(optimization_optimize_forRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public optimization_optimize_forRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_paramsDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnmodel_id;
            
            private DataColumn columnscenario_id;
            
            private DataColumn columncomponent_name;
            
            private DataColumn columnparameter;
            
            private DataColumn columnlower;
            
            private DataColumn columnupper;
            
            private DataColumn columnleader;
            
            private DataColumn columnslave;
            
            internal optimization_paramsDataTable() : 
                    base("optimization_params") {
                this.InitClass();
            }
            
            internal optimization_paramsDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn model_idColumn {
                get {
                    return this.columnmodel_id;
                }
            }
            
            internal DataColumn scenario_idColumn {
                get {
                    return this.columnscenario_id;
                }
            }
            
            internal DataColumn component_nameColumn {
                get {
                    return this.columncomponent_name;
                }
            }
            
            internal DataColumn parameterColumn {
                get {
                    return this.columnparameter;
                }
            }
            
            internal DataColumn lowerColumn {
                get {
                    return this.columnlower;
                }
            }
            
            internal DataColumn upperColumn {
                get {
                    return this.columnupper;
                }
            }
            
            internal DataColumn leaderColumn {
                get {
                    return this.columnleader;
                }
            }
            
            internal DataColumn slaveColumn {
                get {
                    return this.columnslave;
                }
            }
            
            public optimization_paramsRow this[int index] {
                get {
                    return ((optimization_paramsRow)(this.Rows[index]));
                }
            }
            
            public event optimization_paramsRowChangeEventHandler optimization_paramsRowChanged;
            
            public event optimization_paramsRowChangeEventHandler optimization_paramsRowChanging;
            
            public event optimization_paramsRowChangeEventHandler optimization_paramsRowDeleted;
            
            public event optimization_paramsRowChangeEventHandler optimization_paramsRowDeleting;
            
            public void Addoptimization_paramsRow(optimization_paramsRow row) {
                this.Rows.Add(row);
            }
            
            public optimization_paramsRow Addoptimization_paramsRow(int model_id, int scenario_id, string component_name, string parameter, System.Double lower, System.Double upper, bool leader, bool slave) {
                optimization_paramsRow rowoptimization_paramsRow = ((optimization_paramsRow)(this.NewRow()));
                rowoptimization_paramsRow.ItemArray = new object[] {
                        model_id,
                        scenario_id,
                        component_name,
                        parameter,
                        lower,
                        upper,
                        leader,
                        slave};
                this.Rows.Add(rowoptimization_paramsRow);
                return rowoptimization_paramsRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                optimization_paramsDataTable cln = ((optimization_paramsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new optimization_paramsDataTable();
            }
            
            internal void InitVars() {
                this.columnmodel_id = this.Columns["model_id"];
                this.columnscenario_id = this.Columns["scenario_id"];
                this.columncomponent_name = this.Columns["component_name"];
                this.columnparameter = this.Columns["parameter"];
                this.columnlower = this.Columns["lower"];
                this.columnupper = this.Columns["upper"];
                this.columnleader = this.Columns["leader"];
                this.columnslave = this.Columns["slave"];
            }
            
            private void InitClass() {
                this.columnmodel_id = new DataColumn("model_id", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnmodel_id);
                this.columnscenario_id = new DataColumn("scenario_id", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnscenario_id);
                this.columncomponent_name = new DataColumn("component_name", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncomponent_name);
                this.columnparameter = new DataColumn("parameter", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnparameter);
                this.columnlower = new DataColumn("lower", typeof(System.Double), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnlower);
                this.columnupper = new DataColumn("upper", typeof(System.Double), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnupper);
                this.columnleader = new DataColumn("leader", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnleader);
                this.columnslave = new DataColumn("slave", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnslave);
                this.columnmodel_id.AllowDBNull = false;
                this.columnscenario_id.AllowDBNull = false;
                this.columncomponent_name.AllowDBNull = false;
                this.columnparameter.AllowDBNull = false;
                this.columnlower.AllowDBNull = false;
                this.columnupper.AllowDBNull = false;
                this.columnleader.AllowDBNull = false;
                this.columnslave.AllowDBNull = false;
            }
            
            public optimization_paramsRow Newoptimization_paramsRow() {
                return ((optimization_paramsRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new optimization_paramsRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(optimization_paramsRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.optimization_paramsRowChanged != null)) {
                    this.optimization_paramsRowChanged(this, new optimization_paramsRowChangeEvent(((optimization_paramsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.optimization_paramsRowChanging != null)) {
                    this.optimization_paramsRowChanging(this, new optimization_paramsRowChangeEvent(((optimization_paramsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.optimization_paramsRowDeleted != null)) {
                    this.optimization_paramsRowDeleted(this, new optimization_paramsRowChangeEvent(((optimization_paramsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.optimization_paramsRowDeleting != null)) {
                    this.optimization_paramsRowDeleting(this, new optimization_paramsRowChangeEvent(((optimization_paramsRow)(e.Row)), e.Action));
                }
            }
            
            public void Removeoptimization_paramsRow(optimization_paramsRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_paramsRow : DataRow {
            
            private optimization_paramsDataTable tableoptimization_params;
            
            internal optimization_paramsRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableoptimization_params = ((optimization_paramsDataTable)(this.Table));
            }
            
            public int model_id {
                get {
                    return ((int)(this[this.tableoptimization_params.model_idColumn]));
                }
                set {
                    this[this.tableoptimization_params.model_idColumn] = value;
                }
            }
            
            public int scenario_id {
                get {
                    return ((int)(this[this.tableoptimization_params.scenario_idColumn]));
                }
                set {
                    this[this.tableoptimization_params.scenario_idColumn] = value;
                }
            }
            
            public string component_name {
                get {
                    return ((string)(this[this.tableoptimization_params.component_nameColumn]));
                }
                set {
                    this[this.tableoptimization_params.component_nameColumn] = value;
                }
            }
            
            public string parameter {
                get {
                    return ((string)(this[this.tableoptimization_params.parameterColumn]));
                }
                set {
                    this[this.tableoptimization_params.parameterColumn] = value;
                }
            }
            
            public System.Double lower {
                get {
                    return ((System.Double)(this[this.tableoptimization_params.lowerColumn]));
                }
                set {
                    this[this.tableoptimization_params.lowerColumn] = value;
                }
            }
            
            public System.Double upper {
                get {
                    return ((System.Double)(this[this.tableoptimization_params.upperColumn]));
                }
                set {
                    this[this.tableoptimization_params.upperColumn] = value;
                }
            }
            
            public bool leader {
                get {
                    return ((bool)(this[this.tableoptimization_params.leaderColumn]));
                }
                set {
                    this[this.tableoptimization_params.leaderColumn] = value;
                }
            }
            
            public bool slave {
                get {
                    return ((bool)(this[this.tableoptimization_params.slaveColumn]));
                }
                set {
                    this[this.tableoptimization_params.slaveColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_paramsRowChangeEvent : EventArgs {
            
            private optimization_paramsRow eventRow;
            
            private DataRowAction eventAction;
            
            public optimization_paramsRowChangeEvent(optimization_paramsRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public optimization_paramsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_planDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnscenario_id;
            
            private DataColumn columnscenario_name;
            
            private DataColumn columnoptimize_for;
            
            private DataColumn columnnum_steps;
            
            private DataColumn columnmode_exec_id;
            
            private DataColumn columnexplore_mode_id;
            
            private DataColumn columnis_active;
            
            internal optimization_planDataTable() : 
                    base("optimization_plan") {
                this.InitClass();
            }
            
            internal optimization_planDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn scenario_idColumn {
                get {
                    return this.columnscenario_id;
                }
            }
            
            internal DataColumn scenario_nameColumn {
                get {
                    return this.columnscenario_name;
                }
            }
            
            internal DataColumn optimize_forColumn {
                get {
                    return this.columnoptimize_for;
                }
            }
            
            internal DataColumn num_stepsColumn {
                get {
                    return this.columnnum_steps;
                }
            }
            
            internal DataColumn mode_exec_idColumn {
                get {
                    return this.columnmode_exec_id;
                }
            }
            
            internal DataColumn explore_mode_idColumn {
                get {
                    return this.columnexplore_mode_id;
                }
            }
            
            internal DataColumn is_activeColumn {
                get {
                    return this.columnis_active;
                }
            }
            
            public optimization_planRow this[int index] {
                get {
                    return ((optimization_planRow)(this.Rows[index]));
                }
            }
            
            public event optimization_planRowChangeEventHandler optimization_planRowChanged;
            
            public event optimization_planRowChangeEventHandler optimization_planRowChanging;
            
            public event optimization_planRowChangeEventHandler optimization_planRowDeleted;
            
            public event optimization_planRowChangeEventHandler optimization_planRowDeleting;
            
            public void Addoptimization_planRow(optimization_planRow row) {
                this.Rows.Add(row);
            }
            
            public optimization_planRow Addoptimization_planRow(string scenario_name, System.Byte optimize_for, int num_steps, System.Byte mode_exec_id, System.Byte explore_mode_id, bool is_active) {
                optimization_planRow rowoptimization_planRow = ((optimization_planRow)(this.NewRow()));
                rowoptimization_planRow.ItemArray = new object[] {
                        null,
                        scenario_name,
                        optimize_for,
                        num_steps,
                        mode_exec_id,
                        explore_mode_id,
                        is_active};
                this.Rows.Add(rowoptimization_planRow);
                return rowoptimization_planRow;
            }
            
            public optimization_planRow FindByscenario_id(int scenario_id) {
                return ((optimization_planRow)(this.Rows.Find(new object[] {
                            scenario_id})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                optimization_planDataTable cln = ((optimization_planDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new optimization_planDataTable();
            }
            
            internal void InitVars() {
                this.columnscenario_id = this.Columns["scenario_id"];
                this.columnscenario_name = this.Columns["scenario_name"];
                this.columnoptimize_for = this.Columns["optimize_for"];
                this.columnnum_steps = this.Columns["num_steps"];
                this.columnmode_exec_id = this.Columns["mode_exec_id"];
                this.columnexplore_mode_id = this.Columns["explore_mode_id"];
                this.columnis_active = this.Columns["is_active"];
            }
            
            private void InitClass() {
                this.columnscenario_id = new DataColumn("scenario_id", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnscenario_id);
                this.columnscenario_name = new DataColumn("scenario_name", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnscenario_name);
                this.columnoptimize_for = new DataColumn("optimize_for", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnoptimize_for);
                this.columnnum_steps = new DataColumn("num_steps", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnum_steps);
                this.columnmode_exec_id = new DataColumn("mode_exec_id", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnmode_exec_id);
                this.columnexplore_mode_id = new DataColumn("explore_mode_id", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnexplore_mode_id);
                this.columnis_active = new DataColumn("is_active", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnis_active);
                this.Constraints.Add(new UniqueConstraint("OptInfoKey1", new DataColumn[] {
                                this.columnscenario_id}, true));
                this.columnscenario_id.AutoIncrement = true;
                this.columnscenario_id.AllowDBNull = false;
                this.columnscenario_id.ReadOnly = true;
                this.columnscenario_id.Unique = true;
                this.columnscenario_name.AllowDBNull = false;
                this.columnoptimize_for.AllowDBNull = false;
                this.columnnum_steps.AllowDBNull = false;
                this.columnmode_exec_id.AllowDBNull = false;
                this.columnexplore_mode_id.AllowDBNull = false;
                this.columnis_active.AllowDBNull = false;
            }
            
            public optimization_planRow Newoptimization_planRow() {
                return ((optimization_planRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new optimization_planRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(optimization_planRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.optimization_planRowChanged != null)) {
                    this.optimization_planRowChanged(this, new optimization_planRowChangeEvent(((optimization_planRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.optimization_planRowChanging != null)) {
                    this.optimization_planRowChanging(this, new optimization_planRowChangeEvent(((optimization_planRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.optimization_planRowDeleted != null)) {
                    this.optimization_planRowDeleted(this, new optimization_planRowChangeEvent(((optimization_planRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.optimization_planRowDeleting != null)) {
                    this.optimization_planRowDeleting(this, new optimization_planRowChangeEvent(((optimization_planRow)(e.Row)), e.Action));
                }
            }
            
            public void Removeoptimization_planRow(optimization_planRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_planRow : DataRow {
            
            private optimization_planDataTable tableoptimization_plan;
            
            internal optimization_planRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableoptimization_plan = ((optimization_planDataTable)(this.Table));
            }
            
            public int scenario_id {
                get {
                    return ((int)(this[this.tableoptimization_plan.scenario_idColumn]));
                }
                set {
                    this[this.tableoptimization_plan.scenario_idColumn] = value;
                }
            }
            
            public string scenario_name {
                get {
                    return ((string)(this[this.tableoptimization_plan.scenario_nameColumn]));
                }
                set {
                    this[this.tableoptimization_plan.scenario_nameColumn] = value;
                }
            }
            
            public System.Byte optimize_for {
                get {
                    return ((System.Byte)(this[this.tableoptimization_plan.optimize_forColumn]));
                }
                set {
                    this[this.tableoptimization_plan.optimize_forColumn] = value;
                }
            }
            
            public int num_steps {
                get {
                    return ((int)(this[this.tableoptimization_plan.num_stepsColumn]));
                }
                set {
                    this[this.tableoptimization_plan.num_stepsColumn] = value;
                }
            }
            
            public System.Byte mode_exec_id {
                get {
                    return ((System.Byte)(this[this.tableoptimization_plan.mode_exec_idColumn]));
                }
                set {
                    this[this.tableoptimization_plan.mode_exec_idColumn] = value;
                }
            }
            
            public System.Byte explore_mode_id {
                get {
                    return ((System.Byte)(this[this.tableoptimization_plan.explore_mode_idColumn]));
                }
                set {
                    this[this.tableoptimization_plan.explore_mode_idColumn] = value;
                }
            }
            
            public bool is_active {
                get {
                    return ((bool)(this[this.tableoptimization_plan.is_activeColumn]));
                }
                set {
                    this[this.tableoptimization_plan.is_activeColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class optimization_planRowChangeEvent : EventArgs {
            
            private optimization_planRow eventRow;
            
            private DataRowAction eventAction;
            
            public optimization_planRowChangeEvent(optimization_planRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public optimization_planRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
